### ISSUE TITLE
net.dreamlu.mica.http.HttpRequest#bodyJson

### ISSUE THREAD

**Issue by PlexPt** [lets-mica/mica#10]
> public HttpRequest bodyJson(Object body) {
> 		return bodyString(JsonUtil.toJson(body));
> 	}

shoud be 

> public HttpRequest bodyJson(Object body) {
> 		this.requestBody = RequestBody.create(MediaType.get("application/json;charset=UTF-8"), JsonUtil.toJson(body));
> 		return this;
> 	}

or

> `                .addHeader("Content-Type", "application/json;charset=UTF-8")`

**Comment by ChunMengLu** [comment]
收到，感谢反馈！

**Comment by ChunMengLu** [comment]
@PlexPt Fixed，tks~
