### ISSUE TITLE
RequestLogAspect---fun(@RequestBody List<T>) log错误---@see #3

### ISSUE THREAD

**Issue by mangyuan-coding** [lets-mica/mica#13]
![image](https://user-images.githubusercontent.com/45820994/71710307-91f3b100-2e36-11ea-8b89-a5f0c300dbd0.png)
BeanUtil.toMap(Collection<T>) = {empty=false}

**Comment by mangyuan-coding** [comment]
#3 也有提到这个问题，请问哪个版本改动？

**Comment by ChunMengLu** [comment]
see this https://github.com/lets-mica/mica/commit/169e3dda48352461cf1bc31dafa9566b13347317

**Comment by mangyuan-coding** [comment]
3q
