### ISSUE TITLE
mica 1.2.2 计划

### ISSUE THREAD

**Issue by ChunMengLu** [lets-mica/mica#15]
最近几个月将更多的精力放到了 mica 2.0 的设计和开发上。

目前 mica 2.0 已完成，已对 vip 开放。

1.2.2 同步的范围：
1. 工具类类优化。
2. mica 1.x 中的已有模块的增强或优化。
3. 依赖版本的升级和适配。

预计年后 2020-02.02 完成。

**Comment by ChunMengLu** [comment]
由于电脑没带回老家，湖北已经封村，版本延后发布。

**Comment by fengyie007** [comment]
1.2.2啥时候发版？

**Comment by ChunMengLu** [comment]
mica 1.2.2 已经发了，半个小时候应该就能拉到。

**Comment by fengyie007** [comment]
maven库里貌似还没有
