### ISSUE TITLE
关于验证码缓存过期的问题如何解决？

### ISSUE THREAD

**Issue by Wu-XiaoLin** [lets-mica/mica#20]
``mica-captcha`` 项目中的 ``MicaCaptchaServlet`` 未见到已存入缓存却未认证的无效验证码处理。

**Comment by ChunMengLu** [comment]
> `mica-captcha` 项目中的 `MicaCaptchaServlet` 未见到已存入缓存却未认证的无效验证码处理。

配合 mica-plus-redis，cache name 上 `#` 号分割超时时间即可。

**Comment by Wu-XiaoLin** [comment]
``mica-captcha``中使用的Cache未设置有效期，也无法使用``mica-plus-redis``项目设置有效期。

**Comment by Wu-XiaoLin** [comment]
段位太高，看的我有点糊，谢谢！
