### ISSUE TITLE
ip2region.db文件编码有问题 请重新生成 否则mac linux解析乱码 或null

### ISSUE THREAD

**Issue by xiaoyuMo** [lets-mica/mica#22]
ip2region.db文件编码有问题 请重新生成 否则mac linux解析乱码 或null
自行生成后已解决

**Comment by ChunMengLu** [comment]
收到，可以现在配外置的 `ip2region.db`。

**Comment by ChunMengLu** [comment]
测试了一下，除了 region 基本上都是null，的都是有的。

region 我用 go 版也都是 0，你是自己生成的 `ip2region.db` 文件么？

mica 里是直接用的 ip2region 官方的 db 文件。

**Comment by ChunMengLu** [comment]
mac下亲测页ok
