### ISSUE TITLE
【question】redis工具类，使用redisTemplate和JedisPool的应该怎么选择呢？(redis新手)

### ISSUE THREAD

**Issue by mjitigyou** [lets-mica/mica#33]
Please answer some questions before submitting your issue. Thanks!

### Which version of Mica do you using（使用的 mica 版本）?
通用版本
### Expected behavior（预期的效果）
![image](https://user-images.githubusercontent.com/58163564/108626017-00eff700-7489-11eb-8aab-fdd1b2e7cd1f.png)

### Actual behavior（实际的效果）
![image](https://user-images.githubusercontent.com/58163564/108626018-03eae780-7489-11eb-82a9-ed93af61014a.png)

**Comment by ChunMengLu** [comment]
redisTemplate 和 JedisPool 他俩不是竞争关系，你采用 Jedis 配置了 JedisPool，redisTemplate 就会使用 JedisPool
