### ISSUE TITLE
mica-ip2region的memory算法、binary算法、b-tree算法执行结果不一致

### ISSUE THREAD

**Issue by lishangbu** [lets-mica/mica#34]
Please answer some questions before submitting your issue. Thanks!

### Which version of Mica do you using（使用的 mica 版本）?
mica-ip2region 2.4.3-GA
### Expected behavior（预期的效果）
memory算法、binary算法、b-tree算法执行结果一致
### Actual behavior（实际的效果）
memory算法、binary算法可以识别127.0.0.1为内网ip,b-tree算法无法检索到结果
#### memory算法
![image](https://user-images.githubusercontent.com/36465346/110063963-1af1d980-7da7-11eb-8b42-60d931e79c06.png)
#### binary算法
![image](https://user-images.githubusercontent.com/36465346/110064033-45439700-7da7-11eb-994d-7a3c1153586a.png)
#### b-tree算法
![image](https://user-images.githubusercontent.com/36465346/110064109-71f7ae80-7da7-11eb-8d11-cdeba64bf39b.png)

**Comment by ChunMengLu** [comment]
忽略了一个细节，照成 bug 已经修复

**Comment by lishangbu** [comment]
似乎没有完全修复，比如说```223.96.55.5```还是有同样的问题

**Comment by ChunMengLu** [comment]
> 似乎没有完全修复，比如说`223.96.55.5`还是有同样的问题

等 ip2region 下个大版本后在看： https://www.oschina.net/news/132390/ip2region-released-20210309

**Comment by lishangbu** [comment]
明白！
