### ISSUE TITLE
[提问] log4j2 替换为 logback 的考量因素是什么？

### ISSUE THREAD

**Issue by fxbin** [lets-mica/mica#42]
想请教一下 log4j2 替换为 logback 的考量因素是什么？

**Comment by ChunMengLu** [comment]
咩有替换啊，mica-log4j2 私服有的

**Comment by fxbin** [comment]
> 咩有替换啊，mica-log4j2 私服有的

okk，是有注意到新版的mica里面是logback, 之前的老版本我记着有log4j2 , 非常感谢~
