### ISSUE TITLE
为什么要用反人类的gradle啊，构建个项目都能把人整疯

### ISSUE THREAD

**Issue by FFatTiger** [lets-mica/mica#43]
Please answer some questions before submitting your issue. Thanks!

**Comment by ChunMengLu** [comment]
mica 定位为基础组建，直接依赖 jar 使用就行了，每个模块下都有 readme，

基础组建用 gradle 很舒服，没安装 gradle 直接使用 ./gradlew.bat 或 ./gradlew.sh
