### ISSUE TITLE
【开源之夏】mica-openapi 完善，添加配置和认证配置

### ISSUE THREAD

**Issue by ChunMengLu** [lets-mica/mica#44]
开源之夏活动详见：[高校学生参与开源还能拿奖金，开源之夏等你来！](https://mp.weixin.qq.com/s/YZaQaPh9ZEl3EgVAd0qqLQ)

任务说明：
mica-openapi 是对 springdoc-openapi 增强，目前只做了依赖，添加了更好用的 knife4j。

任务步骤：
1. 完成 swagger 配置，具体配置项可参考 mica-swagger。
2. 可配置通用 header 和 oauth2 认证。
3. knife4j 目前需要添加配置才可以展示，检测到 knife4j 添加默认的 env 配置。

**Comment by MessiCY1994** [comment]
亲，你的邮件我已经收到，谢谢
