### ISSUE TITLE
升级3.0.0时，项目构建报错

### ISSUE THREAD

**Issue by the-tsing** [lets-mica/mica#52]
mica-ip2region从2.7.5升级到3.0.0，项目构建报错：
[mica-ip2region](org.springframework.cloud:spring-cloud-dependencies:pom:2022.0.0-RC3 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyun has elapsed or updates are forced)

### Which version of Mica do you using（使用的 mica 版本）?
3.0.0

**Comment by ChunMengLu** [comment]
Spring 的 rc 没在中央库，加 spring 的仓库地址。
