### ISSUE TITLE
JsonView和统一封装返回结果的问题

### ISSUE THREAD

**Issue by yangwenliang123** [lets-mica/mica#53]
项目里很多时候使用统一封装返回结果，例如net.dreamlu.mica.core.result.R类。

public class User {
   public interface UserInfo{};
   public interface UserDetail extends UserInfo{};
   
   private String username;
   private String password;
   @JsonView(UserInfo.class)
   public String getUsername() {
       return username;
   }
   @JsonView(UserDetail.class)
   public String getPassword() {
       return password;
   }
}

@RequestMapping("/user")
@JsonView(User.UserInfo.class)
public User getUser(@RequestParam String username){
   User user = new User();
   user.setUsername("123");
   user.setPassword("123");
   return user;
}

@RequestMapping("/user")
@JsonView(User.UserInfo.class)
public R<User> getUser(@RequestParam String username){
   User user = new User();
   user.setUsername("123");
   user.setPassword("123");
   return R.success(user);
}

在第一个返回中 可以只给前端展示username属性

但是在第二个返回中 用R包装了User对象后，JsonView就失效了，在前端无法获取到User对象的数据。

**Comment by MessiCY1994** [comment]
亲，你的邮件我已经收到，谢谢

**Comment by ChunMengLu** [comment]
@yangwenliang123 这个是 chatgpt 的回答，你试试，可以微调，做的更加完美：

当响应统一包装为`Result<User>`时，`@JsonView`注解无法直接生效。这是因为`@JsonView`注解的作用对象是属性字段，而不是包装类。

为了使`@JsonView`注解生效，你可以通过下面方式来处理：

使用ResponseBodyAdvice：实现`ResponseBodyAdvice`接口，将`@JsonView`注解的配置应用到返回结果上。

```java
@ControllerAdvice
public class JsonViewResponseBodyAdvice implements ResponseBodyAdvice<Object> {
    
    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        return true;
    }
    
    @Override
    public Object beforeBodyWrite(Object body, MethodParameter returnType, MediaType selectedContentType,
            Class<? extends HttpMessageConverter<?>> selectedConverterType, ServerHttpRequest request,
            ServerHttpResponse response) {

        if (body instanceof Result<?>) {
            R<?> result = (Result<?>) body;
            if (result.getData() != null && result.getData() instanceof User) {
                User user = (User) result.getData();
                MappingJacksonValue wrapper = new MappingJacksonValue(user);
                wrapper.setSerializationView(UserViews.Full.class);
                return new Result<>(result.getCode(), result.getMessage(), wrapper);
            }
        }
        
        return body;
    }
}
```

上面的代码中，`JsonViewResponseBodyAdvice`类实现了`ResponseBodyAdvice`接口，并在`beforeBodyWrite`方法中对返回结果进行处理。如果返回结果是`Result<User>`类型且包含非空的`User`对象，则将`User`对象进行包装，并设置视图为`UserViews.Full.class`。

**Comment by ChunMengLu** [comment]
mica-lite 中已经添加支持，详见：https://github.com/lets-mica/mica/blob/master/mica-lite/src/main/java/net/dreamlu/mica/lite/jackson/JsonViewResultAdvice.java

另外需要配置 jackson：https://github.com/lets-mica/mica/blob/master/mica-lite/src/main/java/net/dreamlu/mica/lite/config/MicaLiteConfiguration.java#L40

**Comment by OHUHO** [comment]
我采用了自定义序列化器解决

/**
 * @description: 自定义序列化器，处理JsonView对Result和IPage字段
 * @author: Walker <walker.top@qq.com>
 * @date: 2024-12-14 15:14:14
 * @version: 1.0.0
 */
public class ResultSerializer extends JsonSerializer<Result<?>> {

    private static final String RESULT_CODE = "code";
    private static final String RESULT_MESSAGE = "message";
    private static final String RESULT_DATA = "data";

    private static final String PAGE_TOTAL = "total";
    private static final String PAGE_SIZE = "size";
    private static final String PAGE_CURRENT = "current";
    private static final String PAGE_PAGES = "pages";
    private static final String PAGE_RECORDS = "records";

    @Override
    public void serialize(Result<?> result, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
        jsonGenerator.writeStartObject();
        jsonGenerator.writeNumberField(RESULT_CODE, result.getCode());
        jsonGenerator.writeStringField(RESULT_MESSAGE, result.getMessage());
        jsonGenerator.writeFieldName(RESULT_DATA);

        Object data = result.getData();
        Class<?> activeView = serializerProvider.getActiveView();

        if (data == null) {
            jsonGenerator.writeNull();
        } else {
            serializeData(data, jsonGenerator, serializerProvider, activeView);
        }
        jsonGenerator.writeEndObject();
    }

    /**
     * 序列化Result对象的Data属性
     * @param data data
     * @param jsonGenerator jsonGenerator
     * @param serializerProvider serializerProvider
     * @param activeView activeView
     * @throws IOException exception
     */
    private void serializeData(Object data, JsonGenerator jsonGenerator, SerializerProvider serializerProvider, Class<?> activeView) throws IOException {
        if (activeView == null) {
            // 默认的序列化
            serializerProvider.defaultSerializeField(RESULT_DATA, data, jsonGenerator);
        } else if (data instanceof IPage<?> page) {
            // 序列化Mybatis的Page对象
            serializePage(page, jsonGenerator, activeView, serializerProvider);
        } else {
            // 序列化普通对象
            serializeObject(data, jsonGenerator, activeView, serializerProvider);
        }
    }

    /**
     * 序列化Mybatis的Page对象
     * @param page page
     * @param jsonGenerator jsonGenerator
     * @param activeView activeView
     * @param serializerProvider serializerProvider
     * @throws IOException exception
     */
    private void serializePage(IPage<?> page, JsonGenerator jsonGenerator, Class<?> activeView, SerializerProvider serializerProvider) throws IOException {
        jsonGenerator.writeStartObject();
        jsonGenerator.writeNumberField(PAGE_TOTAL, page.getTotal());
        jsonGenerator.writeNumberField(PAGE_SIZE, page.getSize());
        jsonGenerator.writeNumberField(PAGE_CURRENT, page.getCurrent());
        jsonGenerator.writeNumberField(PAGE_PAGES, page.getPages());
        jsonGenerator.writeFieldName(PAGE_RECORDS);
        serializeObject(page.getRecords(), jsonGenerator, activeView, serializerProvider);
        jsonGenerator.writeEndObject();
    }

    /**
     * 序列化普通对象
     * @param data data
     * @param jsonGenerator jsonGenerator
     * @param activeView activeView
     * @param serializerProvider serializerProvider
     * @throws IOException exception
     */
    private void serializeObject(Object data, JsonGenerator jsonGenerator, Class<?> activeView, SerializerProvider serializerProvider) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.setConfig(serializerProvider.getConfig());
        ObjectWriter writer = mapper.writerWithView(activeView);
        String serializedData = writer.writeValueAsString(data);
        jsonGenerator.writeRawValue(serializedData);
    }
}
