### ISSUE TITLE
Support Springboot 3.2

### ISSUE THREAD

**Issue by aboutZZ** [lets-mica/mica#56]
### Which version of Mica do you using（使用的 mica 版本）?
Mica 3.1.5.1
Springboot 3.2.0
### Expected behavior（预期的效果）
Spring boot application start normally
### Actual behavior（实际的效果）
Error when start up:
```
java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at io.elva.AppServerApplicationKt.main(AppServerApplication.kt:44) [27 skipped]
	... 17 common frames omitted
Wrapped by: java.lang.IllegalStateException: Error processing condition on net.dreamlu.mica.captcha.config.MicaCaptchaAutoConfiguration.imageCaptcha
	at io.elva.AppServerApplicationKt.main(AppServerApplication.kt:44) [17 skipped]

```
### Other information（其他信息）
`factoryBeanObjectType` should either be a Class or a ResolvableType. Now spring throws an exception

**Comment by MessiCY1994** [comment]
亲，你的邮件我已经收到，谢谢

**Comment by aboutZZ** [comment]
可以了，是`Spring cloud openfeign`的锅，还没适配 3.2。但是报错信息怎么跑到 `MicaCaptchaAutoConfiguration` 里面了，日乐购。
