### ISSUE TITLE
HttpRequest connection leaked. 

### ISSUE THREAD

**Issue by PlexPt** [lets-mica/mica#6]
A connection to https://qq.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

code:
`import net.dreamlu.mica.http.HttpRequest;
`
`HttpRequest
                .get("http://ip.sb")
                .log(LogLevel.BODY)
                .execute()
                .asString()
                .trim();`

**Comment by ChunMengLu** [comment]
什么版本，v1.1.9 之前的 asFile 有这个问题。
v1.1.9 mica-http 将 asStream 改成 onStream 避免流未关闭。
asString okhttp 是会 自动关闭的。

**Comment by ChunMengLu** [comment]
@PlexPt 确实好像有这个 问题 body 也需要关闭

**Comment by ChunMengLu** [comment]
不过确实还是有风险，如果没调用这些方法就不会关闭。

**Comment by PlexPt** [comment]
> 不过确实还是有风险，如果没调用这些方法就不会关闭。

确认调用的就是
HttpRequest .get("http://ip.sb") .log(LogLevel.BODY) .execute() .asString() .trim();

**Comment by ChunMengLu** [comment]
> > 不过确实还是有风险，如果没调用这些方法就不会关闭。
> 
> 确认调用的就是
> String string = HttpRequest.post(url)
> .log(LogLevel.NONE)
> .bodyJson(codeBotBean)
> .execute()
> .asString();
> 
> 版本是1.1.8

下一版会测底解决掉这个问题，不过 api 可能会有些变动

**Comment by ChunMengLu** [comment]
1.2.0-SNAPSHOT 版本发布了 api 有所变化，函数式内可以读流，外部会强制关闭。

**Comment by ChunMengLu** [comment]
> 1.2.0-SNAPSHOT 版本发布了 api 有所变化，函数式内可以读流，外部会强制关闭。

api 可以完全兼容，我晚上再调整一下

**Comment by ChunMengLu** [comment]
@PlexPt 1.2.0 已经推送到 maven 中央库，请用该版本试试是否还有类似的问题。
