### ISSUE TITLE
[提问] 关于 redis 分布式限流的疑问

### ISSUE THREAD

**Issue by xkcoding** [lets-mica/mica#7]
https://github.com/lets-mica/mica/blob/5eb918b08f3676f0b2796abd4dad3a252bd4743f/mica-plus-redis/src/main/resources/META-INF/scripts/mica_rate_limiter.lua#L11

https://github.com/lets-mica/mica/blob/5eb918b08f3676f0b2796abd4dad3a252bd4743f/mica-plus-redis/src/main/java/net/dreamlu/mica/redis/ratelimiter/RedisRateLimiterClient.java#L63-L66

以上是 lua 脚本的代码，`now` 的单位是毫秒数，`ttl` 的单位也是毫秒数，为什么需要把 `ttl * 1000` 的操作呢？

**Comment by ChunMengLu** [comment]
可能是个bug，不过不会影响正常使用。

这块是参数的 node-ratelimiter：https://github.com/tj/node-ratelimiter/blob/master/index.js#L65

我猜想他们这里也是之前入参是秒
