### ISSUE TITLE
springboot 2.2.1 Incompatible

### ISSUE THREAD

**Issue by PlexPt** [lets-mica/mica#9]

**Comment by PlexPt** [comment]
java.lang.NoClassDefFoundError: okhttp3/logging/HttpLoggingInterceptor$Level
	at net.dreamlu.mica.http.LogLevel.<clinit>(LogLevel.java:34)

**Comment by PlexPt** [comment]
I added

**Comment by ChunMengLu** [comment]
收到，感谢反馈！
